### ISSUE TITLE
ClearCachedClentID not found

### ISSUE THREAD

**Issue by Wahitler** [Patreo/Tie.Controls.Bootstrap#3]
![image](https://cloud.githubusercontent.com/assets/12858618/20480846/456268e2-b01f-11e6-97ef-4b1559ea08b1.png)

**Comment by ghost** [comment]
I can partially help based on my experiences, The ScriptManager reference issue is because you need to have a reference to System.Web.Extensions from the .Net 2.0 AJAX Web Extensions available from here http://go.microsoft.com/fwlink/?LinkID=77296, as for ClearCachedClientID - I am not sure what this does but I have commented it out for now so I can explore the other controls.
